### PR TITLE
feat: copy collator address

### PR DESCRIPTION
**Pull request by weichweich**
Let's you copy the collator address by clicking on the identicon as you would expect it.
Even gives a nice green background as a feedback that the copy was successful.

Screenshot 2022-07-28 at 14 37 01

### CODE REVIEW

**Comment by tjwelde** [comment]
The green is awful ^^
Can we replace the identicon with a checkmark for a second, or something?

**Comment by weichweich** [comment]
> The green is awful ^^ Can we replace the identicon with a checkmark for a second, or something?

The green is really awful. I wanted to show the text `copied` but couldn't manage to center the text and make it look good. Checkmark would be best i agree. Same circle just with a checkmark instead of the dots maybe.

**Comment by weichweich** [comment]
Updated with a green checkmark

Screenshot 2022-07-29 at 10 45 47

**Comment by weichweich** [comment]
White might even look better

Screenshot 2022-07-29 at 10 48 34

**Review by tjwelde — APPROVED** [review]
LGTM

**Pull request merged**
